// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function GetAIConfig():Promise<store.AIConfig>;

export function SaveAIConfig(arg1:store.AIConfig):Promise<void>;
