// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAIConfig() {
  return window['go']['handler']['AIConfigHandler']['GetAIConfig']();
}

export function SaveAIConfig(arg1) {
  return window['go']['handler']['AIConfigHandler']['SaveAIConfig'](arg1);
}
