// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteHost(arg1) {
  return window['go']['handler']['HostsHandler']['DeleteHost'](arg1);
}

export function ListHosts() {
  return window['go']['handler']['HostsHandler']['ListHosts']();
}

export function SaveHost(arg1) {
  return window['go']['handler']['HostsHandler']['SaveHost'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['handler']['HostsHandler']['TestConnection'](arg1);
}
