// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function DeleteHost(arg1:string):Promise<void>;

export function ListHosts():Promise<Array<store.HostMeta>>;

export function SaveHost(arg1:store.HostInput):Promise<string>;

export function TestConnection(arg1:store.HostInput):Promise<boolean>;
