// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function ApproveCommand(arg1:string,arg2:string):Promise<void>;

export function CancelRun(arg1:string):Promise<void>;

export function DeleteConversation(arg1:string):Promise<void>;

export function ListConversations(arg1:string):Promise<Array<store.Conversation>>;

export function LoadMessages(arg1:string):Promise<Array<store.Message>>;

export function NewSession(arg1:string,arg2:string):Promise<string>;

export function RejectCommand(arg1:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;
