// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveCommand(arg1, arg2) {
  return window['go']['handler']['SessionsHandler']['ApproveCommand'](arg1, arg2);
}

export function CancelRun(arg1) {
  return window['go']['handler']['SessionsHandler']['CancelRun'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['handler']['SessionsHandler']['DeleteConversation'](arg1);
}

export function ListConversations(arg1) {
  return window['go']['handler']['SessionsHandler']['ListConversations'](arg1);
}

export function LoadMessages(arg1) {
  return window['go']['handler']['SessionsHandler']['LoadMessages'](arg1);
}

export function NewSession(arg1, arg2) {
  return window['go']['handler']['SessionsHandler']['NewSession'](arg1, arg2);
}

export function RejectCommand(arg1) {
  return window['go']['handler']['SessionsHandler']['RejectCommand'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['handler']['SessionsHandler']['SendMessage'](arg1, arg2);
}
