// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function ApproveCommand(arg1:string,arg2:string):Promise<void>;

export function CancelRun(arg1:string):Promise<void>;

export function DeleteConversation(arg1:string):Promise<void>;

export function DeleteHost(arg1:string):Promise<void>;

export function GetAIConfig():Promise<store.AIConfig>;

export function ListConversations(arg1:string):Promise<Array<store.Conversation>>;

export function ListHosts():Promise<Array<store.HostMeta>>;

export function LoadMessages(arg1:string):Promise<Array<store.Message>>;

export function NewSession(arg1:string,arg2:string):Promise<string>;

export function RejectCommand(arg1:string):Promise<void>;

export function SaveAIConfig(arg1:store.AIConfig):Promise<void>;

export function SaveHost(arg1:store.HostInput):Promise<string>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function TestConnection(arg1:store.HostInput):Promise<boolean>;
