// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveCommand(arg1, arg2) {
  return window['go']['main']['App']['ApproveCommand'](arg1, arg2);
}

export function CancelRun(arg1) {
  return window['go']['main']['App']['CancelRun'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeleteHost(arg1) {
  return window['go']['main']['App']['DeleteHost'](arg1);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function ListConversations(arg1) {
  return window['go']['main']['App']['ListConversations'](arg1);
}

export function ListHosts() {
  return window['go']['main']['App']['ListHosts']();
}

export function LoadMessages(arg1) {
  return window['go']['main']['App']['LoadMessages'](arg1);
}

export function NewSession(arg1, arg2) {
  return window['go']['main']['App']['NewSession'](arg1, arg2);
}

export function RejectCommand(arg1) {
  return window['go']['main']['App']['RejectCommand'](arg1);
}

export function SaveAIConfig(arg1) {
  return window['go']['main']['App']['SaveAIConfig'](arg1);
}

export function SaveHost(arg1) {
  return window['go']['main']['App']['SaveHost'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
